### ISSUE TITLE
GeneMark page is currently down

### ISSUE THREAD

**Issue by mauriciolangleib** [gatech-genemark/ProtHint#12]
Dear all,

First of all thanks in advance for taking the time to read this message and for developing these tools for biological research!

I'm writing this issue because all of the available links to access to the licenses of GeneMark softwares are down (e.g. http://exon.gatech.edu/). I am currently performing some research analyses while applying to a MSc. degree, and I need the access to tools such as ProtHint and GeneMark-EX.

To be specific, my questions are:

i) Is there a chance that these pages will be up in a short-term period, or we will have to wait some time?
ii) Is there an alternative way to access to such great tools?

Thanks for your time and sorry to bother with this issues.

Best regards,
Mauricio Langleib

**Comment by tomasbruna** [comment]
Dear Mauricio,

we've had a power failure in the main cluster room which hosts the lab servers. The services should be back up this afternoon, sorry for the inconvenience.

Tomas

**Comment by mauriciolangleib** [comment]
Dear Tomas,

Thanks a lot for your quick reply! Now I can access to the programs without inconvenience.

Many thanks, 
Mauricio
