### ISSUE TITLE
error: Alignment is missing after header 

### ISSUE THREAD

**Issue by PeiwenLi** [gatech-genemark/ProtHint#16]
Hi!
I am running ProtHint as implemented in BRAKER2 and encountered the following non-fatal error:
`error: Alignment is missing after header `

I think the error occurred when running the command `run_spliced_alignment.pl` when performing alignment with Spaln. However, the error did not stop the program. Below is the log file:

[braker_38204526.log](https://github.com/gatech-genemark/ProtHint/files/5209919/braker_38204526.log)

What does it mean and what should I do about it? 

Thanks,
Peiwen

**Comment by tomasbruna** [comment]
Hello,

do not worry, about this error, this can rarely happen with Spaln, but usually, a very small number of alignments is affected (in your case, it seems to be 19 / 277028) with no effect on the final result.

I will change this message from `error` to `warning` (or maybe I'll completely suppress it) not to create this confusion.

Thanks,
Tomas
