### ISSUE TITLE
A bug (or feature...) in script 'bin/proteins_from_gtf.pl'

### ISSUE THREAD

**Issue by TypicalSEE** [gatech-genemark/ProtHint#17]
https://github.com/gatech-genemark/ProtHint/blob/d3b3be2889a3607151937bdde25fb35be03da041/bin/proteins_from_gtf.pl#L336

If a fasta sequence has its header like ">0", the above Perl script will exit and print "error, fasta record without definition line found $0: $line\n".

**Comment by tomasbruna** [comment]
Thanks for catching this, that's definitely a bug :)
