### ISSUE TITLE
shell errors? -- grep topProt=TRUE Spaln/spaln.gff > topProteins.gff || [[ $? == 1 ]]

### ISSUE THREAD

**Issue by conchoecia** [gatech-genemark/ProtHint#18]
Hi there, I ran prothint with ~5 million prots from closely related species, also using GMES:

```
ProtHint/bin/prothint.py genome.fasta myprots.pep  --workdir output/prothint --threads 46 --maxProteinsPerSeed 25
```

Seems like the run was going well until this:

```
[Tue Dec  1 13:09:56 2020] Translating coordinates from local pair level to contig level
[Tue Dec  1 13:10:33 2020] Finished spliced alignment
[Tue Dec  1 13:10:34 2020] Processing the output
/bin/sh: 1: [[: not found
[Tue Dec  1 13:12:18 2020] error: ProtHint exited due to an error in command: grep topProt=TRUE Spaln/spaln.gff > topProteins.gff || [[ $? == 1 ]]
```

There are plenty of lines in `Spaln/spaln.gff`. Running `wc -l` shows `4165243 spaln.gff`. Looks like the problem might be that something is calling `/bin/sh` instead of `/bin/bash`? If you think that is what it is, any idea where to change the code to specify the shell? Thanks.

**Comment by tomasbruna** [comment]
Hello @conchoecia,

you are right, the subprocess Python module is calling `/bin/sh` by default. I never caught this problem because `/bin/sh` points to bash on my system.

I made a code change to always use bash. Can you test the code in this branch https://github.com/gatech-genemark/ProtHint/tree/enforce-bash? Please try it with the [example](https://github.com/gatech-genemark/ProtHint/tree/enforce-bash/example) to quickly see if the fix works for you.

Best,
Tomas

**Comment by conchoecia** [comment]
Hi @tomasbruna - I modified the code before I saw your branch. What I did was just add `executable=bin/bash` to the systemCall method. It ran fine, and the output looks like it makes sense.

```
def systemCall(cmd):
    """Make a system call

    Args:
        cmd (string): Command to call
    """
    sys.stderr.flush()
    if subprocess.call(cmd, shell=True, executable = "/bin/bash") != 0:
        sys.exit('[' + time.ctime() + '] error: ProtHint exited due to an ' +
                 'error in command: ' + cmd)
```

In any case, I checked out your branch that you linked, and the example runs through fine. I'll let you know if I run into any more related errors. Thanks!

**Comment by tomasbruna** [comment]
Hi @conchoecia,

your modification is equivalent to the change I did in the new branch. Thanks for reporting this issue, I will merge the fix into the master branch.

Best,
Tomas
