### ISSUE TITLE
Recommended run parameters downstream for braker

### ISSUE THREAD

**Issue by conchoecia** [gatech-genemark/ProtHint#20]
Hi there, just wanted to get your input on what parameters are best to use downstream in braker. Perhaps it would be better if I posted there? The README for this repo suggests `prothint_augustus.gff`, but no parameters for braker. I've tried many configurations from `braker.pl --help` to no avail - each time it crashes for a different reason, usually a missing file.

The evidence that I'm trying to feed braker is a bam of RNA-seq reads aligned to the ref with STAR, and the prothint output from running 70 translated transcriptomes against the reference.

The most recent iteration of braker that I've tried is this:

```
braker.pl --species=my_species --cores={threads} \
        --augustus_args="--singlestrand=true" \
        --genome=ref.fasta \
        --bam=rna_seq_to_ref.sorted.bam \
        --prothints=prothint/prothint.gff --etpmode
```

...based on these clues that I found in the ```braker.pl --help```:

```
--etpmode                           Run GeneMark-ETP with hints provided from
                                    proteins and RNA-Seq data. This mode is not
                                    compatible with using the aligners
                                    GenomeThreader, Exonerate and Spaln (stand alone)
                                    within braker.pl. ProtHint (with Spaln)
                                    as alignment poducing pipeline is
                                    compatible.
--prothints=hints.gff               If BRAKER is called with hints produced
                                    by ProtHint, specify the file
                                    prothint.gff, here. Will possibly concatenated
                                    with hints RNA-Seq hints if called with
                                    --etpmode.
```

I have also tried this incantation, recommended by `braker.pl --help`: `braker.pl [OPTIONS] --genome=genome.fa --hints=proteinintrons.gff --epmode=1`. Howver, I'm not sure if `proteinintrons.gff` is referring to `prothint.gff` or `prothint_augustus.gff`, or something else.

Thanks so much for your suggestions. There are a lot of moving parts in braker and AUGUSTUS, and finding the right combo has been challenging.

**Comment by tomasbruna** [comment]
Hello @conchoecia,

I believe you are working with an older version of BRAKER2. That version had many issues with protein integration. This was recently significantly improved, please get the latest BRAKER2 code from GitHub's master branch (there is not an official release, yet).

Take a look at BRAKER2 readme for more help. Specifically, these 2 sections should be helpful: https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance and  https://github.com/Gaius-Augustus/BRAKER#testing-braker-with-proteins-of-any-evolutionary-distance-and-rna-seq.

> the prothint output from running 70 translated transcriptomes against the reference.

While this might work, ProtHint was designed to map cross-species proteins. I recommend you try supplying such proteins instead (take a look at https://github.com/gatech-genemark/ProtHint#protein-database-preparation).

Best,
Tomas

**Comment by conchoecia** [comment]
Hi @tomasbruna - I think you're right - I appear to have been using an older version of BRAKER.

So, rather than running prothint as a standalone and passing the `prothint_augustus.gff` file, you think it is better/easier to just run something like `braker.pl --genome genome.fa --prot_seq proteins.fa --bam ../RNAseq.bam  --gm_max_intergenic 10000 --etpmode --softmasking --cores N`?

Thanks,
Darrin

**Comment by tomasbruna** [comment]
Yes, BRAKER2 will handle the ProtHint integration, you just need to specify the path to ProtHint with the `--PROTHINT_PATH` option (details here https://github.com/Gaius-Augustus/BRAKER#prothint).

I suggest to first run the [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) in BRAKER2 to make sure everything runs correctly.

Finally, in a real run, do not use the `--gm_max_intergenic 10000` option. This option is there just to speed up the test runs. With real data, it's better to allow for longer intergenic regions.

Best,
Tomas

**Comment by conchoecia** [comment]
Great to know about the `--gm_max_intergenic 10000` option. I had already started a run with that! :)

**Comment by tomasbruna** [comment]
Good to know, I'll update the readme a bit to prevent other people from running with this option.
