### ISSUE TITLE
Prothint version2.5.0 cann't output evidence_augustus.gff file

### ISSUE THREAD

**Issue by 18616831168** [gatech-genemark/ProtHint#21]
Hi,
    When I ran braker2, I found an err that "failed to open file evidence_augustus.gff!" , and finally I located the problem in the evidence_augustus.gff file. I tried to downgrade the protthint program to solve the problem. is it a bug?

best,
Yulin Bai

**Comment by tomasbruna** [comment]
Hello Yulin,

the latest BRAKER2 (from the master branch on its GitHub) is compatible with the new ProtHint version 2.5.0. I'd recommend updating BRAKER2 instead of using an older, compatible, ProtHint.

Best,
Tomas

**Comment by tomasbruna** [comment]
A new BRAKER2 release is coming soon, to prevent issues like this one.
