### ISSUE TITLE
 No homologous proteins were found by DIAMOND

### ISSUE THREAD

**Issue by Huangyizhong** [gatech-genemark/ProtHint#26]
Hi， there
  I have runned the ProHint to map the proteins to the masked genome as follws: /home/goldenpigs217/softwares/ProtHint-2.6.0/bin/prothint.py ./bmxfasta.masked six_protein.fasta --threads 10
But unfortunately, there are something wrong during the process. show as follows 
........................................................
Reported 0 pairwise alignments, 0 HSPs.
0 queries aligned.
[Thu Mar 18 04:10:18 2021] DIAMOND finished
[Thu Mar 18 04:10:18 2021] Preparing pairs for alignments
[Thu Mar 18 04:11:02 2021] Preparation of pairs finished
[Thu Mar 18 04:11:02 2021] Starting spliced alignment with spaln
[Thu Mar 18 04:11:03 2021] Loading alignment pairs into memory
[Thu Mar 18 04:11:03 2021] Pairs loaded. Number of pairs to align: 0
[Thu Mar 18 04:11:03 2021] Starting the alignments
[Thu Mar 18 04:11:03 2021] 0/0 (100%) pairs aligned
[Thu Mar 18 04:11:03 2021] Alignment of pairs finished
[Thu Mar 18 04:11:03 2021] Translating coordinates from local pair level to contig level
[Thu Mar 18 04:11:03 2021] Finished spliced alignment
error: No homologous proteins were found by DIAMOND (/home/goldenpigs217/homology_protein/diamond/diamond.out is empty).
This error can be causedThis error can be caused by:
    a) The set of input proteins is too small and/or the proteins are too remote.
    b) The gene seeds identified by GeneMark-ES (or the supplied gene seeds in case the option "--geneSeeds" was used) are incorrect. Please try running GeneMark-ES separately to 
ProtHint Version 2.6.0
I wonder about it ! The protein fasta file that I provide combines from the six species
![image](https://user-images.githubusercontent.com/31943359/111649957-d141ce00-883f-11eb-98ce-eb0cf629edd9.png)
What should I do to solve this probles? 
Thanks advance!
sincerely
Yizhong Huang

**Comment by tomasbruna** [comment]
Hello Yizhong,

everything looks OK at first glance. Could you share your inputs with me? Please contact me at bruna.tomas@gatech.edu if you don't want to share your inputs publicly here.

I'll try to run ProtHint and see what exactly is going on.

Best,
Tomas

**Comment by Huangyizhong** [comment]
Hi！Thanks so much for your help ! I wlii touch the genome and proteins file there! Thanks
















At 2021-03-19 05:59:29, "Tomáš Brůna" ***@***.***> wrote:

Hello Yizhong,

everything looks OK at first glance. Could you share your inputs with me? Please contact me at ***@***.*** if you don't want to share your inputs publicly here.

I'll try to run ProtHint and see what exactly is going on.

Best,
Tomas

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
six_protein3.rar (41.52M, 2021年4月3日 9:14 到期)
下载
chr18.masked.fa (54.28M, 2021年4月3日 9:22 到期)
下载

**Comment by Huangyizhong** [comment]
Hi, there. Have you complete the test for   ProtHint? I wonder about it ! 
Thanks so much!

**Comment by tomasbruna** [comment]
Hi Yizhong,

I only received the files today, something went wrong when sending the email I guess.

ProtHint works fine for me with the example input you sent. I ran it in two steps as follows:

```
# Generate GeneMark-ES predictions
gmes_petap.pl --seq chr18.masked.fa --cores 16 --ES --verbose
# Run ProtHint
prothint.py chr18.masked.fa six_protein3.fasta --geneSeeds genemark.gtf
```

and I got around 1000 hints from ProtHint.

I do, however, see a potential problem with your input. I noticed you are using hard-masking (replacing all masked regions with N). Please use soft-masking (replacing masked regions with lower-case letters) instead. When the genome is soft-masked, the program can still access the nucleotide sequence inside repeats. With hard-masking, this information is lost. This can lead to poor results because the genome is effectively fragmented into many small chunks by the short hard-masked repeats.

I hope that soft-masking will solve the issue for you.

Best,
Tomas

**Comment by Huangyizhong** [comment]
Hi， Dear


Thanks so much for your help ! I will follow your advice to do the prohint and BRAKER again. I think that all these problems will be solved. Thanks again!
Yizhong Huang 


















At 2021-03-21 00:05:29, "Tomáš Brůna" ***@***.***> wrote:

Hi Yizhong,

I only received the files today, something went wrong when sending the email I guess.

ProtHint works fine for me with the example input you sent. I ran it in two steps as follows:

# Generate GeneMark-ES predictions
gmes_petap.pl --seq chr18.masked.fa --cores 16 --ES --verbose
# Run ProtHint
prothint.py chr18.masked.fa six_protein3.fasta --geneSeeds genemark.gtf


and I got around 1000 hints from ProtHint.

I do, however, see a potential problem with your input. I noticed you are using hard-masking (replacing all masked regions with N). Please use soft-masking (replacing masked regions with lower-case letters) instead. When the genome is soft-masked, the program can still access the nucleotide sequence inside repeats. With hard-masking, this information is lost. This can lead to poor results because the genome is effectively fragmented into many small chunks by the short hard-masked repeats.

I hope that soft-masking will solve the issue for you.

Best,
Tomas

**Comment by Huangyizhong** [comment]
HI， Tomas
 I have runned the ProtHint followed the two steps from you touched.  The first step went well (there was a genemark.gtf file ). But when I conducted the second step, there were errors , which was the same as I posted two days ago. 
![image](https://user-images.githubusercontent.com/31943359/111905836-a26a6880-8a88-11eb-8d48-deaec378e623.png)
Unfortunately,
I want to know that when you run the second step (prothint.py chr18.masked.fa six_protein3.fasta --geneSeeds genemark.gtf), the  N in 'chr18.masked.fa' have been replaced by n? Does the chr18.masked.fa is soft-nasked?
Sorry to disturb you again!
Thanks 
Yizhong Huang

**Comment by tomasbruna** [comment]
Hello,

replacing all `N` with `n` in chr18.masked.fa does not really change anything -- the sequence is still hard-masked. Soft masking indicates masked regions by using lower-case letters. Hard masking overwrites masked regions with a wildcard letter, N for nucleotides or X for proteins [[ref](https://drive5.com/usearch/manual/masking.html#:~:text=Soft%20masking%20indicates%20masked%20regions,nucleotides%20or%20X%20for%20proteins.&text=In%20USEARCH%2C%20masking%20is%20used,excluding%20seeds%20or%20word%20matches.)].

I do not know how you mask your sequence. If you are using RepeatMasker, soft-masking can be triggered by using its `-xsmall` option.

Tomas

**Comment by Huangyizhong** [comment]
Thanks so much. I have used the RepeatMasker with its -xsmall option to mask genome again. And now the process is goning! I will share my results as soon as possible.
Thanks again!
Yizhong Huang 
















At 2021-03-23 02:30:00, "Tomáš Brůna" ***@***.***> wrote:

Hello,

replacing all N with n in chr18.masked.fa does not really change anything -- the sequence is still hard-masked. Soft masking indicates masked regions by using lower-case letters. Hard masking overwrites masked regions with a wildcard letter, N for nucleotides or X for proteins [ref].

I do not know how you mask your sequence. If you are using RepeatMasker, soft-masking can be triggered by using its -xsmall option.

Tomas

**Comment by tomasbruna** [comment]
Great, I'm closing this issue since the problem was solved. Feel free to start a new one if you run into other problems.
