### ISSUE TITLE
grep -P fails in Biocontainers image

### ISSUE THREAD

**Issue by nathanweeks** [gatech-genemark/ProtHint#27]
I observed a few ProtHint errors when attempting to use a Biocontainers build of BRAKER (https://quay.io/repository/biocontainers/braker2 ; quay.io/biocontainers/braker2:2.1.6--hdfd78af_2 ) as a base image with GeneMark (and bundled ProtHint) added:

1.  prothint.py: busybox `grep -P` (Perl regex) isn't supported:
https://github.com/gatech-genemark/ProtHint/blob/b06385a2dfde96920f3fd6d2ee9c7f1d95f74cd3/bin/prothint.py#L199

For portability, could the `-P` option be removed, as it shouldn't be necessary here ~(as `CDS` is treated as a literal, rather than a regexp anyway)?~ (actually, it's "\tCDS\t", but python is treating "\t" as an escape character that's expanded in the python string, resulting in `CDS` flanked by tab characters being used as grep's pattern operand as expected, validated manually by checking the output of: `subprocess.call(["bash", "-c", "grep \tCDS\t test2/longest_seed_isoforms.gtf"])`)

2. spalnBatch.sh: the `readlink -e` option (aka `--canonicalize-existing`) doesn't exist:
https://github.com/gatech-genemark/ProtHint/blob/b06385a2dfde96920f3fd6d2ee9c7f1d95f74cd3/bin/spalnBatch.sh#L21) 

`readlink -f` is supported by busybox `readlink`, and should suffice here (OTOH, the [GNU readlink documentation](https://www.gnu.org/software/coreutils/manual/html_node/readlink-invocation.html#readlink-invocation) recommends using `realpath` in this case, which busybox also supports)

3. spalnBatch.sh: the `stat --printf` option isn't supported:
https://github.com/gatech-genemark/ProtHint/blob/b06385a2dfde96920f3fd6d2ee9c7f1d95f74cd3/bin/spalnBatch.sh#L34
https://github.com/gatech-genemark/ProtHint/blob/b06385a2dfde96920f3fd6d2ee9c7f1d95f74cd3/bin/spalnBatch.sh#L35

`stat -c` is supported by busybox, and is equivalent in this case.

**Comment by tomasbruna** [comment]
Thank you! These are pretty good suggestions, and it's great that you also offered all the alternative commands.

I'll test the changes you suggested when I get a chance, thanks again!

**Comment by tomasbruna** [comment]
Everything works smoothly after making the changes you suggested, thank you :)

 I decided to go with `readlink -f` instead of `realpath` in **2.** because `realpath` is [not pre-installed](https://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f) on many Linux distributions.
