### ISSUE TITLE
Genome is softmasked?

### ISSUE THREAD

**Issue by pjx1990** [gatech-genemark/ProtHint#29]
Is the genome sequence using a softmasked genome? Thx

**Comment by tomasbruna** [comment]
Softmasking is used by GeneMark-ES to predict seed genes (as illustrated [here](https://academic.oup.com/view-large/figure/209721335/lqaa026fig2.jpeg)). Softmasking generally improves the accuracy of GeneMark-ES and this improvement can result in better final predictions.

The rest of ProtHint ignores softmasking. If you are getting gene seeds separately (and giving them to ProtHint with `--geneSeeds` option), it does not matter whether the genome is softmasked.
