### ISSUE TITLE
spaln_boundary_scorer and probuild not working in Braker2 Biocontainer

### ISSUE THREAD

**Issue by qisun2** [gatech-genemark/ProtHint#30]
I am having issues of running ProtHint in Braker Biocontainer, due to spaln_boundary_scorer and probuild missing shared library: libstdc++.so.6. I do not know whether it could be fixed from your side by compiling with static libraries, or I should bring this issue to Biocontainer to add libstdc++.so.6.

**Comment by qisun2** [comment]
Just find out that the binaries included in GeneMark use static libraries.

**Comment by tomasbruna** [comment]
Hi @qisun2,

it's still a good idea to have the `spaln_boundary_scorer` compiled statically in this repository as well, thanks for the suggestions.

I've updated the binary in a1e1a85527c8bc47c598964a75b0568c3477ce8c

Best,
Tomas
