### ISSUE TITLE
 No unique gene seeds were detected

### ISSUE THREAD

**Issue by tinyhys** [gatech-genemark/ProtHint#36]
Hi dear developers, I have failed running braker's test3.sh using --epmode. I have post a same issue under braker repository, but I hardly got reply there... 

The command line is 

```
 ( time braker.pl --PROTHINT_PATH=/export/home/ydn/yty/software/prothint/bin/ --GENEMARK_PATH=/export/home/ydn/yty/software/gmes/ --genome=../genome.fa --prot_seq=../proteins.fa --epmode --softmasking --workingdir=$wd --cores 48 --gm_max_intergenic 10000 ) &> test3.log
```

The log file says

```
...
[Thu Nov 11 01:54:06 2021] Enqueueing pair 5762/5767 (99.9%)
[Thu Nov 11 01:54:11 2021] 5767/5767 (100%) pairs aligned
[Thu Nov 11 01:54:11 2021] Alignment of pairs finished
[Thu Nov 11 01:54:11 2021] Translating coordinates from local pair level to contig level
[Thu Nov 11 01:54:11 2021] Finished spliced alignment
[Thu Nov 11 01:54:12 2021] Flagging top chains
[Thu Nov 11 01:54:12 2021] Processing the output
[Thu Nov 11 01:54:15 2021] Output processed
[Thu Nov 11 01:54:15 2021] ProtHint finished.
#*********
# WARNING: Number of reliable training genes is low (198). Recommended are at least 600 genes
#*********
ProtHint Version 2.6.0
Copyright 2019, Georgia Institute of Technology, USA

Please cite
  - ProtHint: https://doi.org/10.1093/nargab/lqaa026
  - DIAMOND:  https://doi.org/10.1038/nmeth.3176
  - Spaln:    https://doi.org/10.1093/bioinformatics/btn460

Called from: /export/home/ydn/yty/software/braker/example/tests/test3
Cmd: /export/home/ydn/yty/software/prothint/bin//prothint.py --threads=48 --geneSeeds /export/home/ydn/yty/software/braker/example/tests/test3/augustus.hints_iter1.gtf --prevGeneSeeds /export/home/ydn/yty/software/braker/example/tests/test3/GeneMark-ES/genemark.gtf --prevSpalnGff /export/home/ydn/yty/software/braker/example/tests/test3/Spaln/spaln_iter1.gff /export/home/ydn/yty/software/braker/example/tests/test3/genome.fa /export/home/ydn/yty/software/braker/example/tests/test3/proteins.fa

[Thu Nov 11 02:34:55 2021] Pre-processing protein input
ProtHint is running in the iterative mode.
[Thu Nov 11 02:34:55 2021] Selecting a subset of data to run in the next iteration
Warning: No unique gene seeds were detected in the /export/home/ydn/yty/software/braker/example/tests/test3/augustus.hints_iter1.gtf input file. ProtHint will only update seed gene IDs of hints to match the IDs in the new seed gene file.
[Thu Nov 11 02:34:55 2021] Processing the output
error: The "topProt=TRUE" flag is missing in the Spaln/spaln.gff output file. This issue can be caused by the presence of special characters in the fasta headers of input files. Please remove any special characters and re-run ProtHint. See https://github.com/gatech-genemark/ProtHint#input for more details about the input format.
ERROR in file /export/home/ydn/yty/software/links/braker.pl at line 5417
Failed to execute /export/home/ydn/yty/software/prothint/bin//prothint.py --threads=48 --geneSeeds /export/home/ydn/yty/software/braker/example/tests/test3/augustus.hints_iter1.gtf --prevGeneSeeds /export/home/ydn/yty/software/braker/example/tests/test3/GeneMark-ES/genemark.gtf --prevSpalnGff /export/home/ydn/yty/software/braker/example/tests/test3/Spaln/spaln_iter1.gff /export/home/ydn/yty/software/braker/example/tests/test3/genome.fa /export/home/ydn/yty/software/braker/example/tests/test3/proteins.fa!
```

The Spaln/spaln.gff was an empty file.  Could your please give me some advice ? 
Looking forward to you reply, Many thanks!

**Comment by tomasbruna** [comment]
Hi @tinyhys,

thanks for reporting this. There might be an error in BRAKER2/ProtHint when no unique genes are detected in the second iteration (as the message `No unique gene seeds were detected` says). This is a rare case and I never saw it happen, not even in the tests. Therefore, it may be causing some unexpected issues. It is possible that the output of GeneMark changed slightly and this situation now occurs while running the test.

I will debug this on Monday. For now, I think you can try to run the full BRAKER2, because this situation will not occur on a real dataset with many more predicted genes.

Best,
Tomas

**Comment by tinyhys** [comment]
> Hi @tinyhys,
> 
> thanks for reporting this. There might be an error in BRAKER2/ProtHint when no unique genes are detected in the second iteration (as the message `No unique gene seeds were detected` says). This is a rare case and I never saw it happen, not even in the tests. Therefore, it may be causing some unexpected issues. It is possible that the output of GeneMark changed slightly and this situation now occurs while running the test.
> 
> I will debug this on Monday. For now, I think you can try to run the full BRAKER2, because this situation will not occur on a real dataset with many more predicted genes.
> 
> Best, Tomas

Hi Tomas, 
Thanks for your timely reply.
Indeed I have run braker1 and braker2 successfully before, however this time it failed which made things strange. This time I did run the real data using my draft assembly genome and orthoDB10 and I met this issue. I used to think of outdate of gmes license would cause the issue but it not. And maybe there were something happened to my conda environment for annotating in resent days,  I am not sure.
I will rebuilt every soft to test whether it is the error of software itself or it's just my installation fault.
Best ~

**Comment by tomasbruna** [comment]
Thabks for checking the installation! Let me know

**Comment by tinyhys** [comment]
Hi Tomas, I am glad to tell you I might find out what caused the issue and as I expected it was all my fault.

Once I was attempting to find a script to transform gtf to gff and finally I found the **gtf2gff.pl** in AUGUSTUS. However it outputs gtf by default which makes a little inconvenience. So I made a minor modification to make it output gff3 by default. I would never consider that this small change would bring a so strange problem to me many days later!

So I feel so sorry to bother you and I would seek help if I really meet a problem.

Best ~

**Comment by Theo-wang0007** [comment]
> Hi Tomas, I am glad to tell you I might find out what caused the issue and as I expected it was all my fault.
> 
> Once I was attempting to find a script to transform gtf to gff and finally I found the **gtf2gff.pl** in AUGUSTUS. However it outputs gtf by default which makes a little inconvenience. So I made a minor modification to make it output gff3 by default. I would never consider that this small change would bring a so strange problem to me many days later!
> 
> So I feel so sorry to bother you and I would seek help if I really meet a problem. 
> 
> Best ~

Hello, I also met this issue. Could you please tell me more details about how to solve this issue? The command line does not include transform gtf to gff, and the protein.fasta was downloaded from OrthoDB.

**Comment by tinyfallen** [comment]
> > Hi Tomas, I am glad to tell you I might find out what caused the issue and as I expected it was all my fault.
> > Once I was attempting to find a script to transform gtf to gff and finally I found the **gtf2gff.pl** in AUGUSTUS. However it outputs gtf by default which makes a little inconvenience. So I made a minor modification to make it output gff3 by default. I would never consider that this small change would bring a so strange problem to me many days later!
> > So I feel so sorry to bother you and I would seek help if I really meet a problem.
> > Best ~
> 
> Hello, I also met this issue. Could you please tell me more details about how to solve this issue? The command line does not include transform gtf to gff, and the protein.fasta was downloaded from OrthoDB.

Hi,

You could first check if the mediate gtf file's format is correcet or not, otherwise we may not meet the same issue.

In many cases there may not have issues in the termination step but the out files' error in previous steps.

best~
