### ISSUE TITLE
prothint_augustus.gff used for augustus training

### ISSUE THREAD

**Issue by hrluo93** [gatech-genemark/ProtHint#40]
Hi ProtHint，

Training Augustus is a  laborious process. Thank you very much for this excellent tool!

I have some questions about the prothint_augustus.gff
Can this gff directly used for  augustus training ([autoAugTrain.pl](https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/autoAugTrain.pl)) ？ 
in usage --trainingset=prothint_augustus.gff ?

If I can do this, remove bad training genes according to train.err is not needed?

Best wishes!
Ran

**Comment by tomasbruna** [comment]
Hi Ran,

it cannot easily be used directly, but check out BRAKER2 ([paper](https://doi.org/10.1093/nargab/lqaa108), [GitHub](https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance)) -- it uses this file (and GeneMark-EP+) to automatically train AUGUSTUS.

Tomas
