### ISSUE TITLE
Generate ProtHint seed regions without GeneMark-ES

### ISSUE THREAD

**Issue by CuriousTim** [gatech-genemark/ProtHint#41]
I have found GeneMark-ES too slow for my applications. I ran it as a separate step just to try it out and it was running for over 10hrs before I stopped it and it is only one of the three major steps in the GeneMark-EP+ pipeline so that whole process would take a very long time. Is it possible to generate seeds some other way and change some ProtHint parameters to gain speed at the possible expense of accuracy?

One idea to generate seed regions could be to run Diamond against all ORF translations in the genome and then run Spaln in regions with high scoring, same-strand alignments to predict exon/intron boundaries.

Another could be to run MetaEuk and use those predictions as seeds.

The output of these pipelines could be converted into a format similar to the GTF file generated by GeneMark-ES and used with ProtHint.

I am not very familiar with gene prediction processes so I am wondering if these ideas are reasonable.

**Comment by tomasbruna** [comment]
Hi @CuriousTim,

these ideas are very reasonable. In fact, I am working on a ProtHint version that does just that (seeded directly by DIAMOND). Unfortunately, this is still incomplete (the development of this is in a separate branch https://github.com/gatech-genemark/ProtHint/tree/diamond-seeds), and I'm not sure when I'll have enough time to finish it.

Tomas

**Comment by CuriousTim** [comment]
Oh that's cool! Glad to hear there is already development on this front. I will explore other options for now.
