### ISSUE TITLE
proteins_from_gtf.pl issue

### ISSUE THREAD

**Issue by francesco-ricci** [gatech-genemark/ProtHint#49]
Hello, 

I am trying to use the prothint pipeline and one of the commands used in it ([proteins_from_gtf.pl](http://proteins_from_gtf.pl/)) does not produce a .yaml file as reported in the example folder. I am not skilled in perl but I think there is a problem with the code and I was wondering if you guys could please fix it.  

I am attaching a screenshot of my output gene_stat.yaml file. As you can see the contigs code and info are not piled up one after the other, but the produced file has first all the contigs dodes and then all the contigs info.

Thanks
Francesco

<img width="1037" alt="Screen Shot 2022-09-21 at 15 05 27" src="https://user-images.githubusercontent.com/54572239/191418775-f8ad5cb9-7203-4455-a706-d8038f5f8393.png">

**Comment by tomasbruna** [comment]
Hi Francesco,

the file you shared looks OK to me. The contigs seem very short, but that's another topic. Is ProtHint running into errors?

The input in the example has only one contig, so maybe that's why the yaml appears "piled up".

Best,
Tomas

**Comment by francesco-ricci** [comment]
Thanks for your help Tomas. 

When I run the ProtHint pipeline, I get the error message in the attached file. The command nuseq_for_selected_genes.pl uses the .yaml file (generated through the command proteins_from_gtf.pl) at line 52, as highlighted in the error. That's one of the reasons why I thought that's was the problem. 

Cheers
Francesco
<img width="1333" alt="Screen Shot 2022-09-08 at 12 59 31" src="https://user-images.githubusercontent.com/54572239/191631148-0036ca50-5250-410f-b311-d828ac4224fb.png">

**Comment by tomasbruna** [comment]
And when you test ProtHint on [the example](https://github.com/gatech-genemark/ProtHint/tree/master/example), do you get the same error?

**Comment by francesco-ricci** [comment]
yes, just tried same error. 

<img width="1355" alt="Screen Shot 2022-09-22 at 10 44 32" src="https://user-images.githubusercontent.com/54572239/191634257-87663f05-efc4-4a98-85e0-701de905a65a.png">

**Comment by tomasbruna** [comment]
Ok, this means that something is wrong with the installation of the YAML package. Did you install it with the following command or similarly?

    cpan MCE::Mutex threads YAML

**Comment by francesco-ricci** [comment]
just tried again and it looks fine 
<img width="1050" alt="Screen Shot 2022-09-22 at 10 50 01" src="https://user-images.githubusercontent.com/54572239/191634759-10c3321a-eca9-46fb-a405-3a0c3bd1e993.png">

**Comment by tomasbruna** [comment]
That seems fine... Maybe try installing with conda (https://anaconda.org/bioconda/perl-yaml) and not as a super user.

**Comment by francesco-ricci** [comment]
Already tried, it doesn't work.

**Comment by francesco-ricci** [comment]
I actually get this error message when I try to install cpan without sudo.
<img width="1595" alt="Screen Shot 2022-09-22 at 11 05 10" src="https://user-images.githubusercontent.com/54572239/191636176-6cc6485f-57da-40f4-b207-61044f5ad0e0.png">

**Comment by tomasbruna** [comment]
Those are probably related, but I'm no expert at installing Perl packages :/

**Comment by francesco-ricci** [comment]
Fixed it!

I created another environment and reinstalled all the dependencies from scratches and now it works.
