### ISSUE TITLE
set.out error?

### ISSUE THREAD

**Issue by mabh5** [gatech-genemark/ProtHint#54]
I am trying to run ProtHint to generate a .gff file to run in BRAKER. I am trying to align over 1 million protein sequences against a 2.2 GB genome. I am running this program on a local computer with 18 cores with 36 processors. I ran the program over the weekend and it seemed to run for a while (over 24 hours) before I got the following error: 

> training level ES_A: /mnt/e/GTCCSCombined/ragtag_outputA/Annotation/GeneMark_ES/run/ES_A_1
> error, file not found /home/mh/gmes_linux_64/parse_set.pl: set.out
> error on call: /home/mh/gmes_linux_64/parse_set.pl --section ES_A --cfg  /mnt/e/GTCCSCombined/ragtag_outputA/Annotation/GeneMark_ES/run.cfg  --v
> [Sat Apr  1 17:21:20 2023] error: ProtHint exited due to an error in command: gmes_petap.pl --verbose --cores 36 --ES --seq /mnt/e/GTCCSCombined/ragtag_outputA/Annotation/corrected_scaffoldsmasked.fasta --soft auto

I am not overly familiar with coding and so I am struggling with figuring out exactly what went wrong. I looked into the gmes.txt file that was created in the ProtHint process and it wasn't very helpful for understanding what went wrong. 

Advice is welcome. I am also wondering if it is possible to start the program back up where it failed rather then having to run the whole thing again? 

thanks!

**Comment by tomasbruna** [comment]
Hi @mabh5, GALBA seems more appropriate for a genome of this size (as you already discovered). I'm closing this issue and let's continue on solving it in https://github.com/Gaius-Augustus/GALBA/issues/29
