### ISSUE TITLE
Could not find gmes_petap.pl in the PATH

### ISSUE THREAD

**Issue by karthickbrlab** [gatech-genemark/ProtHint#58]
[Thu Dec 14 16:06:20 2023] Pre-processing protein input
[Thu Dec 14 16:06:36 2023] Running GeneMark-ES.
[Thu Dec 14 16:06:36 2023] warning: Could not find gmes_petap.pl in dependencies/GeneMarkES/ folder. Attempting to use gmes_petap.pl in the PATH.
[Thu Dec 14 16:06:36 2023] error: Could not find gmes_petap.pl in the PATH

i have manually added the script over there, but getting same error

**Comment by tomasbruna** [comment]
If GeneMark-ES is available in your `$PATH`, it should be found when you execute `gmes_petap.pl` on the command line (in any folder). You can use this to check its availability before running ProtHint.

If the problem persists, you can run GeneMark-ES separately and give the result to ProtHint with the `--geneMarkGtf` flag.

**Comment by karthickbrlab** [comment]
Thanks, I will!

**Comment by karthickbrlab** [comment]
hi..
I checked the installation of genemark from check_install.bash
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found


Then i ran genemark  by 

perl gmes_petap.pl genome.fasta 

error, unexpected argument found on command line: gmes_petap.pl /home/ubuntu/genome.fasta



How to run genemark.

**Comment by tomasbruna** [comment]
Like so

    gmes_petap.pl --ES --seq genome.fa --soft_mask auto --verbose --cores N

**Comment by karthickbrlab** [comment]
Yeah i did so

and got
# check before the run
error, code cannot be executed in installation folder.

**Comment by tomasbruna** [comment]
Try running from a fresh work directory.

**Comment by karthickbrlab** [comment]
Thanks.

worked well
