### ISSUE TITLE
error: No spliced alignments were created by Spaln 

### ISSUE THREAD

**Issue by karthickbrlab** [gatech-genemark/ProtHint#59]
Hi
I tried to annotate in Braker, found this error related to genemark
i rerun genemark separately, yet found spaln.gff is empty.
 
cat: nuc_2091718_prot_2091718: No such file or directory
rm: cannot remove 'nuc_2091718_prot_2091718': No such file or directory
/home/ubuntu/deru/Deru_data/genemark/ProtHint/spalnBatch.sh: line 61: /home/ubuntu/deru/Deru_data/genemark/ProtHint/../dependencies/spaln_boundary_scorer: No such file or directory
cat: nuc_2091719_prot_2091719: No such file or directory
rm: cannot remove 'nuc_2091719_prot_2091719': No such file or directory
[Thu Apr 4 09:58:25 2024] 2091719/2091719 (100%) pairs aligned
[Thu Apr 4 09:58:25 2024] Alignment of pairs finished
[Thu Apr 4 09:58:25 2024] Translating coordinates from local pair level to contig level
[Thu Apr 4 09:58:28 2024] Finished spliced alignment
error: No spliced alignments were created by Spaln (/home/ubuntu/BRAKER/scripts/braker/Spaln/spaln.gff is empty).

This error can be caused by:
a) The set of input proteins is too small and/or the proteins are too remote.
b) The gene seeds identified by GeneMark-ES (or the supplied gene seeds in case the option "--geneSeeds" was used) are incorrect. Please try running GeneMark-ES separately to identify errors related to gene seeds (https://github.com/gatech-genemark/ProtHint#genemark-es).

ERROR in file braker.pl at line 5355
Failed to execute /home/ubuntu/genemark/ProtHint/prothint.py --threads=1 --geneMarkGtf /home/ubuntu/BRAKER/scripts/braker/GeneMark-ES/genemark.gtf /home/ubuntu/BRAKER/scripts/braker/genome.fa /home/ubuntu/BRAKER/scripts/braker/proteins.fa!

**Comment by tomasbruna** [comment]
Hi @karthickbrlab,

can you share the full stderr log? I'm curious whether the ProtHint problems start with not finding `nuc_2091718_prot_2091718` or earlier.

Tomas

**Comment by karthickbrlab** [comment]
stderr.log is empty.

I can share braker.log,

[braker.log](https://github.com/gatech-genemark/ProtHint/files/14880788/braker.log)


I tried running prothint using genemark.gtf file obtained from genemark es. this again created error at cat: nuc_2091718_prot_2091718: No such file or directory
rm: cannot remove 'nuc_2091718_prot_2091718': No such file or directory.

is this error from prothint or spaln

**Comment by tomasbruna** [comment]
Do you see the following log inside braker work dir `GeneMark-ETP/prothint_gmst.log`? That should have the info.

> is this error from prothint or spaln

Hard to say, can you share the inputs with me (you can email me at bruna.tomas@gmail.com)? I'll run it next week to see if I can reproduce the error.

**Comment by karthickbrlab** [comment]
here is the log file.

But it has run genemark es instead genemark etp

although i mentioned --etpmode

**Comment by karthickbrlab** [comment]
HI,

I freshly installed genemark and checked installation by ./check_install
.bash
but when I run braker, it shows an error.

**Comment by karthickbrlab** [comment]
i have all perl dependencies including YAML. but it throws this error.

**Comment by tomasbruna** [comment]
Hi @karthickbrlab,

I don't see it attached, can you try again?

Tomas

**Comment by karthickbrlab** [comment]
Hi
Problem with prothint has solved, just came out well after reinstallation.

Kindly let me know, how can i use isoseq data in braker?
I have processed and mapped.bam for isoseq data.
can i use same protocols for rna seq data in braker?

**Comment by karthickbrlab** [comment]
hi..
I have installed singularity, and created Braker container. I have Isoseq sets for different tissues, can i catenate the bam files to single bam file and run braker?
Secondly, can i use protein.fa from any closely related species or should i go for the whole viridiplantae proteins for good annotation

kindly provide your suggestions
Thank you
